src/actions/creators/index.js, src/actions/types/index.js, src/components/Entry/DomainArchitectures/IDAResults.js, src/components/Entry/DomainArchitectures/__snapshots__/test.js.snap, src/components/Entry/DomainArchitectures/index.js, src/components/Entry/DomainArchitectures/style.css, src/components/Entry/DomainArchitectures/test.js, src/components/SearchByIDA/IdaEntry.js, src/components/SearchByIDA/__snapshots__/test.js.snap, src/components/SearchByIDA/index.js, src/components/SearchByIDA/style.css, src/reducers/ui/idaAccessionDB/index.js, src/reducers/ui/index.js
Improvements on the Search by IDA:
* The domains can be dragged to reorder them.
* A domain that matches an accession, is painted with the color of it
* Changing the display of pfam or InterPro accessions is now in the redux state
* Minor style fixes.
=> Reordering ida

src/components/ProtVista/Popup/ColorScale/index.js, src/components/ProtVista/Popup/Conservation/index.js, src/components/ProtVista/Popup/Entry/index.js, src/components/ProtVista/Popup/Hydro/index.js, src/components/ProtVista/Popup/Residue/index.js, src/components/ProtVista/Popup/index.js, src/components/ProtVista/index.js, src/components/Protein/Sequence/index.js
Cleaning up the ProtVista component.
* Separating the code for the popups in protvista
* Removing some code that wasn't in use anymore (e.g. mobidb as memberDB)
* Interpro type web element only displayed for interpro entries
* Entry popups now include a button linking to the sequence tab.
FIX #202 The sequence tab now syncs with customLocation, so show the selected region in the hash URL; and inversely to select an area based on the hash URL.
=> Protvista refactor

config.yml.example, src/components/Description/index.js, src/components/Entry/Summary/index.js, src/components/Set/SetLinkFromEntry/index.js
The subpage for sets in an entry is a bit of an overkill, as an entry can only belong to a single set.
So instead of a page with a list of 1 set, this PR shows a link to the set in the overview entry page.
=> Set in entry overview

src/utils/processDescription/descriptionToDescription/index.js
As pointed by typhaine there are cases in the browse section where the active class of the selected endpoint is not applied.
For example:
To get to this state, go to https://www.ebi.ac.uk/interpro/protein/UniProt/entry/pfam/taxonomy/uniprot/10090/?search=#table and then select other member DB.
The problem is that the new location includes the taxonomy values of the old URL, even if its flag `isFilter` is now `null`.
I have added some logic on `descriptionToDescription` that cleans any data in the new location that doesn't belong to the main endpoint or `isFilter!==true`.
I don't think there are side effects of this strategy, but I would like another set of eyes in it, as  `descriptionToDescription` is used in every single link in the page.
=> cleaning description

src/components/Protein/Isoforms/Selector/index.js, src/components/Protein/Isoforms/Viewer/index.js, src/components/Protein/Summary/__snapshots__/test.js.snap, src/components/Protein/Summary/index.js, src/components/Protein/Summary/style.css, src/components/Protein/Summary/test.js, src/components/Related/DomainsOnProtein/index.js, src/components/SimpleCommonComponents/FullScreenButton/index.js, stories/Link.stories.js
A few improvements when displaying protein isoforms:
* The selected isoform is now included in the URL (e.g. `protein/UniProt/P31749/?isoform=P31749-2`) and corresponding part of the redux state (e.g. `{customLocation: {search: {isoform: 'P31749-2'}, ...}, ...}`)
* The order and groups on the protvista graphic for an isoform is similar to the one for a protein. Only missing residues and extra features because that data is not available for isoforms
* When an isoform is selected, it could be displayed fullscreen together with the protein for comparison purposes.
=> Isoforms improvements

src/components/ProtVista/Options/index.js, src/components/ProtVista/index.js
Fix: #296 
The `<Options>` component only set the ColorBy setting dispatching an action.
The actual effect of coloring by is now in the `componentDidUpdate` of `<ProtVista>`
=> "Color by" propagates to multiple protvista instances in the same page

src/components/IPScan/Actions/__snapshots__/test.js.snap, src/components/IPScan/Actions/index.js, src/components/IPScan/Actions/style.css, src/components/IPScan/Actions/test.js, src/components/IPScan/IPScanVersionCheck/index.js, src/components/IPScan/Status/index.js, src/components/IPScan/Summary/IPScanTitle/index.js, src/components/IPScan/Summary/index.js, src/reducers/jobs/index.js, src/reducers/jobs/metadata/index.js, src/store/enhancer/jobs-middleware/index.js
A few changes related in the interproscan results area:
1. Save in Browser moved to the actions row in the result's summary.
2. New state for a job: `saved in browser` to differentiate wwwprod jobs that have been saved from loaded files.
3. The mismatched version warning has been updated to include a message when there is a new version of InterProData and wwwprod hasn't updated interproscan.
=> Minor ipscan changes

src/components/IPScan/Actions/index.js, src/components/IPScan/Actions/style.css, src/components/IPScan/AdvancedOptions/index.js, src/components/IPScan/IPScanVersionCheck/index.js, src/components/IPScan/Search/__snapshots__/test.js.snap, src/components/IPScan/Search/index.js, src/components/IPScan/Summary/index.js, src/pages/Sequence/index.js, src/store/enhancer/jobs-middleware/index.js, src/styles/interpro-new.css, src/utils/cached-fetch/index.js
Resolves #363 
A new action to re-run a job is now included in the overview of an existing job. This option is only available when a there is a version mismatch.
When the user clicks on the rerun button, the search by sequence page is open pre filling the sequence and the advanced options. The capability of pre-fill the advanced options.
=> Rerun ipscan

src/components/Matches/index.js, src/components/Related/RelatedTable/index.js, src/components/Set/Summary/index.js, src/components/Tabs/index.js, src/pages/Download/InterPro/index.js, src/pages/Download/InterProScan/index.js, src/pages/Download/Pfam/index.js, src/pages/Download/index.js, src/pages/Home/index.js
This includes a set of changes to be ready for the decommission of the Pfam website.
* Announcement in the home page the Pfam website is to be retired
* Links to IDA and seed alignments added in Pfam sets, while listing the entries.
* The downloads page now is split in tabs:
* InterPro
* InterProScan
* Pfam **(new)**
=> Pfam changes

src/components/BrowseTabs/BrowseTabsLink/index.js, src/components/EntryMenu/EntryMenuLink/index.js, src/subPages/EntryAlignments/index.js
This PR updates the `<select>` element listing available alignments (Pfam and InterPro entries only) so the number of sequences is displayed:
Requires REST API changes described in ProteinsWebTeam/interpro7-api#88.
=> Show number of sequences

config.yml.example, src/components/ProtVista/Popup/Entry/index.js, src/components/ProtVista/Popup/index.js, src/components/ProtVista/index.js, src/components/ProtVista/style.css, src/components/Table/index.js, src/higherOrder/loadData/defaults/index.js, src/menuConfig.js, src/schema_org/processors.js, src/subPages/Subfamilies/index.js, src/subPages/index.js, src/utils/url/index.js
Adding a subpage for panther families to list the subfamilies related to it.
It also adds a section in the popups in the protein viewers where a panther family matches, indicating which subfamily is responsible for the match.
A small improvement in the way the protvista popups work was made to avoid the creation of multiple react roots and instead reuse the first one that was created.
**Note:** It requires the API change in https://github.com/ProteinsWebTeam/interpro7-api/pull/89
=> Subfamilies

src/components/IPScan/Actions/Group/index.js, src/components/IPScan/Actions/__snapshots__/test.js.snap, src/components/IPScan/Actions/index.js, src/components/IPScan/Actions/style.css, src/components/IPScan/AdvancedOptions/__snapshots__/test.js.snap, src/components/IPScan/AdvancedOptions/index.js, src/components/IPScan/AdvancedOptions/style.css, src/components/IPScan/ImportResultSearch/LoadedFileDialog/index.js, src/components/IPScan/ResultImporter/index.js, src/components/IPScan/Search/__snapshots__/test.js.snap, src/components/IPScan/Search/index.js, src/components/IPScan/Search/style.css, src/components/IPScan/Search/test.js, src/components/IPScan/Status/__snapshots__/test.js.snap, src/components/IPScan/Status/index.js, src/components/IPScan/SubJobsBrowser/index.js, src/components/IPScan/SubJobsBrowser/style.css, src/components/IPScan/Summary/IPScanTitle/index.js, src/components/IPScan/Summary/index.js, src/components/Table/Body/index.js, src/components/Table/index.js, src/components/Table/views/Table/index.js, src/components/Title/index.js, src/components/Title/style.css, src/pages/Sequence/index.js, src/store/enhancer/jobs-middleware/index.js, src/subPages/Sequence/index.js, src/utils/processDescription/handlers/index.js
The purpose of this PR is to support the submission of multiple sequences to the InterProScan web service. 
Several changes were required in order to get this working:
1. Updates in the checks done in the textarea for the sequence
2. Updates in the "automatic clean" function to avoid deleting sequences and prevent 2 fasta headers without content
3. The results are now displayed on a "local-first" basis. Only if there is no data in IndexedDB, check the web service.
4. Each sequence on a job receives the ID of the job concatenated with a suffix `-n` where n is the position on the results file.
5. Multiple sequences are grouped in the job list, using the same logic as nucleotide files.
6. A selector of sequences in the same job was added at the top of the results page.
7.  Importing a job by …
=> Multiple sequence search

src/components/Entry/Summary/index.js, src/components/Set/ClanViewer/index.js, src/components/Set/Summary/index.js, src/components/SimpleCommonComponents/DropDownButton/style.css, src/components/home/ByMemberDatabase/__snapshots__/test.js.snap, src/components/home/ByMemberDatabase/index.js, src/pages/Entry/index.js, src/pages/Home/index.js, src/utils/processDescription/handlers/index.js, src/utils/url-patterns/index.js
All links to pfam.xfam.org have been updated to point to the InterPro website or remove the link.
The announcement on the home page is updated to indicate the Pfam website has been decommissioned and InterPro is the new home for that data.
While updating the links on the Set page, I did a small refactoring, splitting the ClanViewer in its own component for clarity.
=> Removing Pfam links to pfam.xfam.org

src/components/EntryMenu/EntryMenuLink/index.js, src/menuConfig.js
This PR accommodates two data changes for the upcoming release:
- the counter for RoseTTAFold structures has been renamed from `RoseTTAFold` to `rosettafold`
- the number of proteins with an AlphaFold model is calculated for all entries, and not only InterPro/Pfam: 51c075f3c7ba039f566e2b5ba4f7e614bf6c1bd6 adds a condition to only display the menu link for InterPro/Pfam entries
=> Release91 struct models

src/components/AlphaFold/Model/index.js, src/components/AlphaFold/ProteinTable/index.js, src/components/ExtLink/index.js, src/components/ProtVista/Popup/ColorScale/index.js, src/components/ProtVista/Popup/Confidence/index.js, src/components/ProtVista/Popup/Entry/index.js, src/components/ProtVista/Popup/Entry/style.css, src/components/ProtVista/Popup/index.js, src/components/ProtVista/index.js, src/components/ProtVista/style.css, src/components/Structure/ViewerAndEntries/ProtVistaForAlphaFold.js, src/subPages/AlphaFoldModelSubPage/index.js
Alphafold provides a JSON that has the lPDDT score per amino acid, for example for the [Q8I3H7 model](https://alphafold.ebi.ac.uk/files/AF-Q8I3H7-F1-confidence_v3.json). 
We are now retrieving this file when displaying the protein viewer at the side of an alphafold model in order to generate a track that shows this information in the context of the protein sequence.
This PR uses the nightingale coloured track, defining the sequence for it as the categories retrieved on the file (`"D" |  "L" | "M" | "H"`) and defining the attributes of the track as:
```html
<protvista-coloured-sequence
scale="H:90,M:70,L:50,D:0"
color_range="#ff7d45:0,#ffdb13:50,#65cbf3:70,#0053d6:90,#0053d6:100"
...
/>
```
Other changes included in this PR:
* The Color Scale in the PopUps now support scales with multiple …
=> confidence track

src/components/ProtVista/index.js
FIX #425 
it concatenates `-n` on accessions that come from Pfam-N to avoid using the same ID as an Unintegrated pfam track
=> Bugfix pfam-n + unintegrated pfam

package-lock.json, src/components/GoTerms/List/index.js, src/components/GoTerms/__snapshots__/test.js.snap, src/components/GoTerms/index.js, src/components/GoTerms/style.css, src/components/Protein/PantherGoTerms/index.js, src/components/Protein/PantherGoTerms/style.css, src/components/Protein/Summary/__snapshots__/test.js.snap, src/components/Protein/Summary/index.js, src/components/Related/DomainsOnProtein/index.js, src/subPages/Subfamilies/index.js
This PR lists the GO terms provided by panther in 2 parts:
1. In the protein page if the protein has a match with a panther family, the client retrieves the information of the subfamily matching, including its Go terms and displays them under the list of InterPro GO terms. e.g. `/protein/uniprot/A0A010R210/`
2. In the subfamilies subpage, as an additional column on the list of subfamilies. It only displays the first 10 GO terms, with the option to display more on demand. e.g. `/entry/panther/PTHR10026/subfamilies`
This requires the changes on the API that are part of https://github.com/ProteinsWebTeam/interpro7-api/pull/92
=> GO terms for Subfamilies

.eslintrc.js, src/components/AlphaFold/Model/index.js, src/components/AlphaFold/selectors.js, src/components/EntryMenu/EntryMenuLink/AlphaFoldMenuLink.js, src/components/ProtVista/Popup/Entry/index.js, src/components/ProtVista/Popup/index.js, src/components/ProtVista/index.js, src/components/Protein/Summary/__snapshots__/test.js.snap, src/components/Related/DomainsOnProtein/index.js, src/components/Structure/ViewerAndEntries/ProtVistaForAlphaFold.js, src/subPages/AlphaFoldModelSubPage/index.js
Adds the AlphaFold confidence track in the protein viewer of the protein page
Removes the hydrophobicity track.
Refactor the way we get the data for the confidence track so it can be reused.
=> Confidence track in the protein page

src/subPages/Curation/index.js
When downloading the HMM model, the extension is `.hmm` but the file is gzip-compressed, which puzzled some users. This PR adds the `.gz` suffix.
=> Add .gz suffix to download file name

src/index.template.html, src/pages/Home/index.js, tsconfig.json, webpack.config.js
Our webpack configuration was set up to create 2 bundles: 1 for modern browsers and 1 for legacy browsers that don't support es-modules.
Checking the stats of the last 7 days from the [livelogs](http://ves-ebi-2e.ebi.ac.uk/es/livelogs/#dashboard/temp/AYc32qFSLmmAsU_n8B8d), from 2356060 hits requesting `*.js` files from the interpro machines, only  4821 hits were requesting `*legacy*` files; for a total 0.2%.
This PR removes the `legacy` bundle, and adds warning messages to upgrade browsers for the affected cases. 
The particular change pushing in this direction is that Lit elements are highly dependent on classes, so adapting Nightingale components would require effort tuning the already complex webpack/babel/typescript setup. An effort that is hard to justify for such a small amount of …
=> removing legacy bundle

src/components/IPScan/Summary/serializers.js, src/components/TimeAgo/__snapshots__/test.js.snap
A user recently reported that their InterProScan results were not available in the website because a component crashed.
This is due to a PIRSR match that does not have any site annotations, which is not expected to happen. The job in question is https://www.ebi.ac.uk/interpro/result/InterProScan/iprscan5-R20230612-090754-0435-27808602-p1m/
Here's a snippet to find the PIRSR match:
```js
const response = await fetch('https://www.ebi.ac.uk/Tools/services/rest/iprscan5/result/iprscan5-R20230612-090754-0435-27808602-p1m/json');
const payload = await response.json();
const empty = payload.results[0].matches.filter((m,) => m.locations[0].sites !== undefined && m.locations[0].sites.length === 0);
```
This PR adds a check to the deserialization to ignore site matches without site annotations. …
=> Fix empty PIRSR site matches

config.yml.example, src/components/Genome3D/index.ts, src/components/Menu/SideMenu/ServerStatus/index.js, src/components/Protein/Summary/__snapshots__/test.js.snap, src/components/ProteinViewer/LabelsInTrack/ExceptionalLabels/index.tsx, src/components/ProteinViewer/Options/index.tsx, src/components/ProteinViewer/Popup/DisProt/index.tsx, src/components/ProteinViewer/Popup/Entry/index.tsx, src/components/ProteinViewer/Popup/Entry/style.css, src/components/ProteinViewer/Popup/Genome3D/index.tsx, src/components/ProteinViewer/Popup/Positions/index.tsx, src/components/ProteinViewer/Popup/Positions/style.css, src/components/ProteinViewer/Popup/RepeatsDB/index.tsx, src/components/ProteinViewer/Popup/index.tsx, src/components/ProteinViewer/TracksInCategory/index.tsx, src/components/ProteinViewer/index.tsx, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/DisProt/index.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/RepeatsDB/index.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/index.tsx, src/components/Related/DomainsOnProtein/index.tsx, src/custom.d.ts, src/pages/Settings/index.js, src/reducers/settings/category/index.js, src/reducers/settings/index.js, src/reducers/status/servers/index.js, src/reducers/status/servers/server/index.js, src/reducers/status/servers/test.js, src/store/utils/get-initial-state/index.js
The main feature added in this PR is the support of 2 new external sources to the `ProteinViewer` on the protein page:
*DisProt* and *RepeatsDB*.
The logic to display *Genome3D* annotations has been updated to follow the same strategy as the 2 DBs above. i.e. Making them part of the `ExternalSourcesHOC`.
All of the external sources are in a category that by default is close, and the label of each feature starts with its source, e.g. `DisProt:`. Popup components were created for each external source.
The server settings for genome 3d have been removed, also the status of it in the side menu has been removed.
The position of a feature in the popups was abstracted as a separate component to reuse it in the external sources popups.
**NOTE 1:** Please review first #489 
**NOTE 2:** Add this to …
=> External sources for the protein viewer

src/components/ProteinViewer/index.tsx, src/components/Related/DomainsOnProtein/index.tsx
Resolves two bugs found in the protein viewer:
* #502: allows the viewer to load even when no entry matches are found
* #503: fixes broken link to MobiDB (and other external resources where the protein accession is part of the URL)
=> Protein viewer fixes

src/components/ProteinViewer/Popup/RepresentativeDomain/index.tsx, src/components/ProteinViewer/RepresentativeDomainsTrack/index.tsx, src/components/ProteinViewer/TracksInCategory/index.tsx, src/components/ProteinViewer/index.tsx, src/components/ProteinViewer/utils.ts, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx, src/components/Related/DomainsOnProtein/index.tsx, src/components/Related/DomainsOnProtein/mergeResidues.ts, src/custom.d.ts
Adds a new category in the protein viewer: **Representative Domains**
Uses a similar algorithm to the one provided by @typhainepl in [the demo](https://github.com/ProteinsWebTeam/pronto/blob/c296c6a987e6d0d999b9dbfd90266f955d6efd17/pronto/api/single_dom.py).
Doesn't have a label on the right, any suggestions for it are welcome, but I thought that given the title of the category, a label wasn't necessary.
=> Single domain track

src/components/EntryMenu/EntryMenuLink/style.css, src/components/File/TooltipContent/style.css, src/components/ProteinViewer/grid.css, src/components/Related/DomainEntriesOnStructure/GoToProtVistaMenu/index.tsx, src/components/Related/DomainEntriesOnStructure/index.tsx, src/components/SimpleCommonComponents/DropDownButton/style.css, src/components/SimpleCommonComponents/Tooltip/index.tsx, src/components/SimpleCommonComponents/Tooltip/style.css, src/components/Structure/Summary/__snapshots__/test.js.snap, src/components/Structure/Summary/index.tsx, src/components/Table/Exporter/index.js, src/reducers/settings/category/index.js
**"Jump To" button**
Hidden. I think there a downstream event listener that breaks the "Jump to" functionality by jumping back to the structure viewer, but I don't have the time to investigate more.
**Relative time**
Showing absolute time instead of relative time (e.g. `31 October 1993` instead of `29 years ago`).
**Performance**
Not done.
I tried to transform the "Jump To" button into a selector so we only show one protein viewer (for one chain) at a time. It works at first, but then there is an unexpected behavior when "cycling back" to the first selected chain (e.g. `A` selected -> switch to `B` -> switch back to `A`).
**Redundancy**
Not done. We need to be able to group chains together based on their sequence. Although this could be done directly in the client (we have the sequence …
=> Structure sequence fix

src/components/Entry/RemovedEntrySummary/index.js, src/components/Entry/Summary/SidePanel/index.tsx, src/components/Entry/Summary/index.tsx, src/custom.d.ts, src/pages/endpoint-page.js
Show basic information for deleted signatures and refactor the information displayed for deleted InterPro entries:
- update error message on top
- show the type and source of the deleted entry
- show the short name, if any
- for signatures, show the member database
- show past names and short names, if any
You do not need to have a local API: you can use `http://wp-np3-af.ebi.ac.uk/interpro/api/` in `config.yml`.
* `/entry/pfam/PF00256/`
* `/entry/ncbifam/TIGR00108/`
* `/entry/cdd/CD00020/`
* `/entry/InterPro/IPR000005/`
=> Removed signatures

src/components/Description/DescriptionFromIntegrated/index.tsx, src/components/Description/DescriptionLLM/__snapshots__/test.js.snap, src/components/Description/DescriptionLLM/index.tsx, src/components/Description/DescriptionLLM/test.js, src/components/Entry/Summary/index.tsx, src/custom.d.ts
This PR adds descriptions of protein families to the entry summary (on the _Overview_ page).
The logic works for any InterPro entry, or member database signature, but right now we only have descriptions for about 5,500 unintegrated PANTHER families.
Local copy on the `dev` branch or  `http://wp-np3-af.ebi.ac.uk/interpro/api/`.
- `/interpro/entry/panther/PTHR24026`
- `/interpro/entry/panther/PTHR24150`
- `/interpro/entry/panther/PTHR39490`
- `/interpro/entry/panther/PTHR43367`
- `/interpro/entry/panther/PTHR46792`
=> AI-generated descriptions

src/components/ProteinViewer/utils.ts, src/custom.d.ts
Representative domains are now selected during the data warehouse build process, and are available in the REST API. 
Local copy on the `dev` branch, or `http://wp-np3-af.ebi.ac.uk/interpro/api/`.
=> Use pre-selected representative domains

src/pages/endpoint-page.js
`endpoint-page.js` implements the logic to display the overview summary of primary endpoints, show the basic information if an InterPro entry or member database signature has been removed, or show error messages (for instance if there is no data returned by the API).
I previously, re-ordered some of the conditions, but this caused an issue when open a entry page for a PANTHER subfamily (`204` returned by the API), but since `payload` is null the client kept showing a "loading" state.
This PR fixes the order of conditions to test to show data or redirect.
=> Fix endpoint page loading

src/higherOrder/loadData/defaults/index.js
Getting counters from the API is an expensive operation, especially on big lists.
Although this requires more investigation to be able to generalise it, it seems to me that for sets the counters in a page like https://www.ebi.ac.uk/interpro/set/pfam/CL0010/entry/pfam/#table are not necessary. I couldn't find any case where they are currently used.
The code change is minimal, but I'm afraid of any cases I miss, so I'd appreciate a check before merging!
=> set subpages without counters

.prettierrc, src/components/Protein/Isoforms/Viewer/index.tsx, src/components/ProteinViewer/utils.ts, src/components/Related/DomainEntriesOnStructure/__snapshots__/test.js.snap, src/components/Related/DomainEntriesOnStructure/index.tsx, src/components/Related/DomainsOnProtein/index.tsx, src/components/Structure/ViewerAndEntries/ProteinViewerForAlphafold/index.tsx, src/components/Structure/ViewerAndEntries/ProteinViewerForStructures/index.tsx
Adding the track for Representative domains in different sections of the website:
* Structures. Handling multiple chains, e.g. http://localhost:8000/interpro/structure/PDB/15c8/#table
* Alphafold. e.g. http://localhost:8000/interpro/protein/unreviewed/R7T3V2/alphafold/
* Isoforms. e.g. http://localhost:8000/interpro/protein/UniProt/P90897/?isoform=P90897-3
Note: There are a few minor style changes in some of the docs because I activated the settings we had for JS files for TS ones.
=> Representative domains everywhere

src/components/Matches/EntriesOnStructure/index.tsx
Fixes #556 (which occurs when a signature does not have a short name) by not passing the `entry.name` object to `EntryPopup`.
=> Fix EntryOnStructure popup

package-lock.json, package.json, scripts/README.md, scripts/browse-with-puppetteer.js, src/components/Matches/FileExporter/index.tsx, src/higherOrder/loadData/defaults/index.js, src/higherOrder/loadData/defaults/relatedCounters.ts, src/higherOrder/loadData/defaults/test.js, src/pages/Proteome/index.js, src/pages/Set/index.js, src/pages/Taxonomy/index.js
On this PR I went through all the usages of `extra_fields=counters` and started using the new feature to specify particular counters to be included to reduce response times.
Additionally, there is a new script that uses `puppeteer` to visit all the combinations of filters in the browse area, and that way a local API can generate the `request.log` with all the recent URLs and we can use that to generate the next release cache.
This becomes necessary as many URLs to be cached have changed to the new granular counters format.
Also while checking this, please have a look at this [commit in the deployment scripts repo](https://github.com/ProteinsWebTeam/InterPro7-extra/commit/a057aed4090cd390c337f9961da9c20442a91dbe) which is a modification to the script that gets the URL from the live …
=> Granular counters

src/components/Entry/CrossReferences/index.tsx
Stop forcing cross-reference database names to uppercase.
=> Do not convert external resource name to upper case

src/components/AlphaFold/ProteinTable/index.tsx, src/components/Matches/index.tsx, src/components/Protein/Card/index.tsx, src/pages/Protein/index.js, src/subPages/SimilarProteins/Table/index.tsx
Changing the icons we use next to the accession of reviewed UniProtKB entries and making the text in the tooltip more consistent.
=> Update icon used for reviewed proteins

config.yml.example, src/components/Proteome/Summary/RfamLink/index.tsx, src/components/Proteome/Summary/UniProtDescription/index.tsx, src/components/Proteome/Summary/index.tsx, src/custom.d.ts
2 additions to the proteome page:
* An external link to Rfam: this one checks first the EBI search index of RFam to see if there is info there  for the given proteome
* A description directly fed from the UniProt API
=> Proteome page improvements

patches/@nightingale-elements+nightingale-msa+4.5.0.patch, src/components/DownloadForm/URLParameters/index.js, src/components/File/FileButton/index.tsx, src/components/File/TooltipContent/index.tsx, src/components/Help/Documentation/index.js, src/components/ProteinViewer/style.css, src/components/Related/Taxonomy/Sunburst/style.css, src/components/Set/ClanViewer/index.tsx, src/components/Structure/Viewer/index.tsx, src/components/Structure/Viewer/style.css, src/components/ToggleSwitch/index.tsx, src/components/ToggleSwitch/style.css, src/subPages/SimilarProteins/index.tsx, webpack.config.js
A collection of small fixes reported on GH issues:
* FIX #580: There is a bug in nightingale where the `height` parameter of the interpro track is not doing anything. It has been reported, but on the interpro website we will avoid this issue by setting a `max-height` in the container div.
* FIX #575: Now it detects if the command or alt button are pressed while clicking on a Pfam entry on the clan visualization, and if so, opens the link in a new tab.
* FIX #564: The problem comes down to NIghtingale using a different syntax for web workers, as it is using rollup and not webpack to bundle the components. Webpack5 is supposed to support the same syntax, so I tried to move into that, but I didn't manage, and after many hours trying different setups, I gave up and changed the nightingale …
=> Minor issues

src/components/Matches/index.tsx, src/higherOrder/loadData/defaults/index.js, src/higherOrder/loadData/defaults/test.js, src/pages/Entry/index.js
Add a column showing the short name of the entry/signature, e.g.
* InterPro entries: `/interpro/entry/InterPro/#table`
* Pfam signatures: `/interpro/entry/pfam/#table`
* NCBIfam signatures matching `A0A000`: `/interpro/protein/UniProt/A0A000/entry/ncbifam/#table`
* PIRSF signatures found in the _Hibiscus syriacus_ proteome: `/interpro/proteome/uniprot/UP000436088/entry/pirsf/#table`
=> Display short names

scripts/browse-with-puppetteer.js, src/components/AlphaFold/Model/index.tsx, src/components/Protein/Summary/index.tsx, src/components/Structure/Summary/__snapshots__/test.js.snap, src/components/Structure/Summary/index.tsx, src/custom.d.ts
Add links to Foldseek so users can perform protein structure searches. Links are added on the summary pages of PDBe structures (e.g. `/interpro/structure/PDB/10gs/`) and protein pages (if an AlphaFold prediction is available, e.g. `/interpro/protein/unreviewed/A0A009GN48/`).
=> Links to Foldseek

src/components/Entry/Summary/Wikipedia/index.tsx, src/components/Entry/Summary/__snapshots__/test.js.snap, src/components/Entry/Summary/index.tsx, src/components/Entry/Summary/style.css, src/custom.d.ts
The website now expects the Wikipedia field to be an array of objects.
And with it, it organizes the different articles in tabs at the end of the entry summary page.
Example PF00001
=> Multiple wikipedia pages

src/components/Entry/Summary/Wikipedia/index.tsx
The text for the caption in wikipedia panels might have links to wiki articles with the syntax `[[ link ]]`.
This PR parses those to create the links to the right place in wikipedia.
=> wikipedia links in caption

src/components/ProteinViewer/utils.ts, src/types/interpro-payloads.d.ts
The first representative domain selection algorithm was evaluating fragments independently, i.e. one fragment from one domain could be selected as representative, but not the other fragment(s).
I changed that, and for the past few months, the `representative` boolean has been available at both the `entry_protein_locations` and `fragments` levels, e.g. [A0A023HJ61](https://www.ebi.ac.uk/interpro/api/entry/all/protein/UniProt/A0A023HJ61/).
This PR changes the source of `representative` to use the one at the location level.
The `representative` property will stopped being added at the fragment level for the next release.
=> Get representative boolean from location instead of fragment

src/pages/Release_notes/index.js
Addresses the issue reported in #639 (to reproduce, head to https://www.ebi.ac.uk/interpro/release_notes/ and click "Show Previous Releases).
=> Sort InterPro releases by version number

src/components/IPScan/Status/__snapshots__/test.js.snap, src/components/IPScan/Status/index.js
Adds a warning about the upcoming version of ipscan results. Informing the users that old results will be incompatible and encourage them to save their jobs.
=> Warning for IPScan pages update

src/components/Entry/Summary/__snapshots__/test.js.snap, src/components/Entry/Summary/index.tsx
Changed the position of references as requested in [IBU-11215](https://www.ebi.ac.uk/panda/jira/browse/IBU-11215).
- The references are now above the GO Terms (e.g. IPR 000003)
- The references are now in the same section of the description, so that if the right section is too long, they don't get pushed down (e.g. IPR000001)
=> Moved reference section below description

src/components/Matches/EntriesOnProtein/__snapshots__/test.js.snap, src/components/Matches/EntriesOnProtein/index.tsx, src/components/Matches/EntriesOnStructure/__snapshots__/test.js.snap, src/components/Matches/EntriesOnStructure/index.tsx, src/components/Matches/StructureOnProtein/__snapshots__/test.js.snap, src/components/Matches/StructureOnProtein/index.tsx, src/components/Matches/style.css, src/components/ProteinViewer/style.css
The column displaying tracks kept expanding for some entries. max-width was required
Closes #637. The example reported was about entry [PF11133](https://www.ebi.ac.uk/interpro/entry/pfam/PF11133/structure/PDB/#table).
=> Fixed matches expanding column

src/components/Matches/index.tsx, src/pages/Protein/index.js, src/subPages/SimilarProteins/Table/index.tsx
Tiny PR that simply changes the text of the link to the AlphaFold page, and the header of the link's column.
=> Make text in cell shorter

src/components/Matches/EntriesOnProtein/__snapshots__/test.js.snap, src/components/Matches/EntriesOnProtein/index.tsx, src/components/Matches/EntriesOnStructure/__snapshots__/test.js.snap, src/components/Matches/EntriesOnStructure/index.tsx, src/components/Matches/StructureOnProtein/__snapshots__/test.js.snap, src/components/Matches/StructureOnProtein/index.tsx, src/components/ProteinViewer/style.css, src/components/Table/views/Tree/index.tsx, src/components/Table/views/Tree/style.css, src/components/Tree/style.css
Improved the taxonomy tree bar following [IBU-11216](https://www.ebi.ac.uk/panda/jira/browse/IBU-11216)
- Removed the taxon id, now just the name is displayed;
- Removed tooltips;
- Replaced the dropdown selector with a breadcrumb (*important note below)
The result comes down to this:
* NOTE
Something weird happens when you jump from a taxon to another. The selector (now the breadcrumbs), takes into account all the taxon visited, and not just the ones relevant to the current focus. Shouldn't the example below be something like (ROOT / VIRUS / OVALIVIRIDAE) ? 
Is this an * actual * bug or am I missing something? I've implemented a couple of solutions but they all end up having a couple of problems that I think require @gustavo-salazar's guidance to be solved.
=> Improved taxonomy tree bar 

src/components/Entry/EntryListFilters/AIGeneratedFilter/index.tsx, src/components/Entry/EntryListFilters/GOTermsFilter/index.tsx, src/components/Entry/EntryListFilters/__snapshots__/test.js.snap, src/components/Entry/EntryListFilters/index.tsx
This PR adds an AI filter to the Browse page for InterPro and MemberDBs entries.
- The filter follows the same logic of the GOTerm filter.
- It's not shown if there's no LLM generated entries for a MemberDB (e.g. Pfam)
=> AI Filter for entries

src/components/ContentFromRST/index.js
Properly formats reStructuredText links that do not take the full length of the line.
Example: www.ebi.ac.uk/interpro/help/training/
The link to the application of the next InterPro course is not properly formatted on the live website.
=> Inline RST links

src/components/Protein/Isoforms/Viewer/index.tsx, src/components/ProteinViewer/LabelsInTrack/ExceptionalLabels/index.tsx, src/components/ProteinViewer/Options/style.css, src/components/ProteinViewer/Popup/Entry/index.tsx, src/components/ProteinViewer/Popup/Residue/index.tsx, src/components/ProteinViewer/Popup/index.tsx, src/components/ProteinViewer/ShowMoreTracks/index.tsx, src/components/ProteinViewer/ShowMoreTracks/style.css, src/components/ProteinViewer/TracksInCategory/index.tsx, src/components/ProteinViewer/grid.css, src/components/ProteinViewer/index.tsx, src/components/ProteinViewer/style.css, src/components/ProteinViewer/utils.ts, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx, src/components/Related/DomainsOnProtein/index.tsx, src/components/Related/DomainsOnProtein/mergeResidues.ts, src/components/Structure/ViewerAndEntries/ProteinViewerForAlphafold/index.tsx, src/types/external-payloads.d.ts, src/utils/entry-color/index.js
This PR:
- Reorganizes tracks on the Protein summary page and hides (but makes expandable) all the ones considered "secondary". See [IBU-11247](https://www.ebi.ac.uk/panda/jira/browse/IBU-11247) for more;
- Adds representative family track;
- Adds disordered regions track;
- Changes the residue track so that domains are not shown;
- The logic for fetching PTM data is added but currently not used given the non-completeness of the PTM data;
=> Reorganize tracks

src/components/ProteinViewer/TracksInCategory/index.tsx, src/reducers/settings/category/index.ts
Update the following default options in the protein viewer:
- label by: replace `accession` and `short name` by `name` and `short name`
- color by: replace `accession` by `member database`
=> Update default options

src/actions/creators/index.ts, src/actions/types/index.ts, src/components/Download/Actions/index.js, src/components/Download/Summary/index.js, src/components/DownloadForm/Controls/index.tsx, src/components/File/index.tsx, src/components/SearchResults/index.tsx, src/reducers/download/index.ts, src/types/state.d.ts, src/web-workers/download/index.worker.js
Currently, when listing [download jobs](https://www.ebi.ac.uk/interpro/result/download/#table), the first column is the URL to the API page used to fetch records. This can be confusing for non-technical users, but also can be misleading as results may span over several pages instead of all being returned by one page.
This PR adds some logic to keep track of the URL of the page where the download job was created.
Example to test:
1. Go to `/entry/InterPro/?type=active_site`
2. Open the _Download_ dropdown
3. Click _Generate TSV_
4. Go to `/result/download/` or `Results > Your downloads`
Live website:
This branch:
The first column is now a link to the _website_ page where the download job was created. The link to the first page of the API has been moved under "Actions".
=> Add link to page where download job was initiated

src/components/IPScan/Status/SequenceList/index.tsx
If you open an InterProScan search that you haven't started yourself, your browser doesn't have job metadata like the creation date/time, which causes the the expiry date to epoch + one week (so 8 January 1970).
Example: https://www.ebi.ac.uk/interpro/result/InterProScan/iprscan5-R20250320-100548-0158-19647556-p1m/#table
This small PR hides the expiry date if it's in the past.
=> Hide expiry date if in the past

src/components/Related/DomainEntriesOnStructure/index.tsx, src/components/Structure/Summary/index.tsx, src/components/Structure/Viewer/index.tsx, src/components/Structure/ViewerAndEntries/EntrySelection/index.tsx, src/components/Structure/ViewerAndEntries/index.tsx
- the SCOP link is now the correct one;
- ProteinViewers are grouped by chain sequence (see 8v11);
- Highlight menu now displays names, not accessions;
- StructureViewer reset button works again.
=> Structure page fixes and improvements

config.yml.example, config/dev_config.yml, config/master_config.yml, config/staging_config.yml, src/components/ProteinViewer/LabelsInTrack/ExceptionalLabels/index.tsx, src/components/ProteinViewer/LabelsInTrack/index.tsx, src/components/ProteinViewer/LabelsInTrack/style.css, src/components/ProteinViewer/Popup/DisProt/index.tsx, src/components/ProteinViewer/Popup/RepeatsDB/index.tsx, src/components/ProteinViewer/Popup/TED/index.tsx, src/components/ProteinViewer/Popup/index.tsx, src/components/ProteinViewer/RepresentativeDomainsTrack/index.tsx, src/components/ProteinViewer/TracksInCategory/index.tsx, src/components/ProteinViewer/index.tsx, src/components/ProteinViewer/utils.ts, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/utils.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/DisProt/index.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/RepeatsDB/index.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/TED/index.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/index.tsx, src/components/Related/DomainsOnProtein/utils.ts, src/components/Structure/ViewerAndEntries/ProteinViewerForAlphafold/index.tsx, src/reducers/settings/category/index.ts, src/reducers/settings/index.ts, src/store/utils/get-initial-state/index.js, src/types/external-payloads.d.ts, src/types/interpro-payloads.d.ts, src/types/state.d.ts, src/utils/entry-color/index.js
This PR fetches TED domains from the TED API ~~_via_ the InterPro API (see ProteinsWebTeam/interpro7-api#178)~~. TED domains are shown under the representative domains section. They stay visible in summary/overview mode and are displayed on the protein overview page and the AlphaFold subpage.
> [!CAUTION]
> The EMBL-EBI domains have been whitelisted, so the TED API can be used on our frontend. However, a local instance running on `localhost` will still experience CORS issues. As a workaround, use `https://matthiasblum.fr/ted/` as a proxy instead of `https://ted.cathdb.info/`.
Other changes:
- RepeatsDB
- Moved from the _External sources_ section to the _Domains_ section
- Displaying individual units instead of the full consensus
- DisProt:
- Moved from the _External sources_ section to …
=> TED domains and minor other changes

src/components/Structure/ViewerAndEntries/ProteinViewerForPredictedStructure/index.tsx
Noticed that the InterPro-N callout isn't displayed on the AlphaFold and BFVD subpages. This PR fixes it.
=> InterPro-N callout

src/utils/entry-color/index.js
When coloring by domain relationship, the error below is raised for tracks without a proper parent, e.g. unintegrated signatures, residue tracks, etc.
> TypeError: e.parent.accession is undefined
This PR adds a quick check to prevent this error.
=> Check that parent.accession is not undefined

config/master_config.yml, config/staging_config.yml, src/components/Matches/index.tsx, src/pages/Protein/index.tsx, src/subPages/SimilarProteins/Table/index.tsx
This PR adds to following:
- fix for the two config files that are missing the `bfvd` subpages
- links from the protein tables to the BFVD subpage (at the moment, the "Predicted Structure" column shows a link to the AlphaFold subpage, but if the protein has a BFVD prediction, it shows nothing)
=> BFVD extra

src/components/ProteinViewer/TracksInCategory/index.tsx, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx, src/components/Structure/ViewerAndEntries/ProteinViewerForPredictedStructure/index.tsx
This PR addresses the following fixes:
- Repeats were .. repeated.. because of a mismatch domain != repeat between child and parent element. (`A0A084B9Z8`); 
- BFVD fixed highlighting on click now works;
- Some matches aren't displayed when opening the page. Didn't experience the problem again. Will have to check if that happens once published on `wwwdev`.
=> BFVD and Repeat fixes

src/components/ProteinViewer/index.tsx, src/components/ProteinViewer/style.css, src/components/Related/DomainEntriesOnStructure/index.tsx, src/styles/interpro-vf.css
This PR changes how bottom margins are used for the domain viewer, i.e. only use larger margins, required to show the Options menu with the InterPro-N options, when we have non-structure proteins.
It also slightly reduces the domain viewer and its title.
=> Minor change to domain viewer margins

src/components/Header/index.js, src/components/SearchByText/TextSearchBox/index.tsx
- incomplete/incorrect data loading when redirection to a protein page happens after pressing enter in the search box in the header; 
- no automatic redirection/search initiation while the user is typing. The search action needs to be confermed by either pressing enter or by clicking on the search button;
- disabled usage of "search" history hints that caused the previously typed string to always reappear in the search box;
=> Improve Search Bar in Header

src/components/IPScan/AdvancedOptions/index.tsx, src/components/IPScan/Summary/serializers.ts, src/components/Related/DomainsOnProtein/DomainsOnProteinLoaded/index.tsx
- the unintegrated section of the IPScan Job results still contained some matches due to missing type in data coming in from IPScan. Now that the type is available, we can place them in the correct section.
- advanced options for job submission improvements, as outlined in: [IBU-11828](https://embl.atlassian.net/browse/IBU-11828)
=> Improved options and unintegrated matches type for IPScan Jobs

src/components/SearchResults/__snapshots__/test.js.snap, src/components/SearchResults/index.tsx, src/components/Structure/ViewerAndEntries/ProteinViewerForPredictedStructure/index.tsx, src/components/Structure3DModel/3DModel/index.tsx
- Exporter menu is back on the text search page;
- If the model was rotated and a track was hovered over, moving the mouse out of the track caused the model to be reset to its initial position.
- If a track was clicked to keep a match highlighted on the structure, and the cursor was then moved to hover over another track, both matches were highlighted, using the color of the first selected match.
=> Structure model fixes, exporter for text search

src/components/SearchByText/TextSearchBox/index.tsx, src/components/SearchByText/index.tsx
- **clicking** on the Search button in the Seach by Text section didn't perform any action. Now the search works correctly and the automatic redirect behavior has been implemented for this case too;
- Removed the empty select menu with the "No option" caption that constantly appeared under the SearchBox;
- the Clear button now correctly clears the text box if the search hasn't happened yet.
=> Search button improvements

src/utils/removed-pages/index.tsx
This PR fixes the redirection from the curation subpage to the main/overview page of Pfam entries.
We moved the curation details from the curation subpage to the overview page, but the link in the warning message adds an `/overview` at the end of the URL.
Example: https://www.ebi.ac.uk/interpro/entry/pfam/PF03106/curation/
=> Curation subpage to overview redirect

src/components/Structure/ViewerAndEntries/EntrySelection/index.tsx, src/components/Structure/ViewerAndEntries/index.tsx
The message showing "No entry matches this structure" is showing while the page is loading, even if the structure _has_ entry matches, e.g. [2eho](https://www.ebi.ac.uk/interpro/structure/PDB/2eho/).
This PR propagates the `isReady` boolean down to the `EntrySelection` component so the message is only displayed if there are no matches _and_ the page is loaded (ready).
=> Do not show no-entries callout while loading

src/components/home/BlogEntries/__snapshots__/test.js.snap, src/components/home/BlogEntries/index.tsx
This PR addresses [IBU-11885](https://embl.atlassian.net/browse/IBU-11885).
Now both feeds (InterPro blog and EMBL-EBI news) are retrieved, merged and ordered by date (for the InterPro blog ones string matching on the URL is used to get the date). 
Only doubts I have are: 
- should we keep displaying just 3/4 of them as it is now, or should we increase that number?
- which badge/image do we display for EMBL-EBI articles? Right now they're the same as the non-focused InterPro blog posts.
=> EMBL Articles

config/dev_config.yml, config/master_config.yml, config/staging_config.yml, src/components/ProteinViewer/Popup/TED/index.tsx, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/TED/index.ts, src/components/Related/DomainsOnProtein/ExternalSourcesHOC/index.tsx, src/reducers/settings/category/index.ts, src/reducers/settings/index.ts, src/store/utils/get-initial-state/index.js, src/types/external-payloads.d.ts, src/types/state.d.ts
Switches to using the AlphaFold API instead of the TED API to retrieve TED domains, mainly so we can display the Q-score.
=> TED using AlphaFold API
