.eslintrc.js, package.json, src/actions/creators/index.js, src/actions/index.js, src/actions/types/index.js, src/components/EMBLDropdown/__snapshots__/test.js.snap, src/components/EMBLDropdown/index.js, src/components/Menu/InterProMenu/index.js, src/components/Menu/SideMenu/ServerStatus/index.js, src/components/Menu/SideMenu/ServerStatus/style.css, src/components/Menu/SideMenu/index.js, src/components/Structure/StructureListFilters/ResolutionFilter/index.js, src/pages/Settings/index.js, src/reducers/index.js, src/reducers/settings/category/test.js, src/reducers/status/browser/index.js, src/reducers/status/browser/test.js, src/reducers/status/index.js, src/reducers/status/servers/index.js, src/reducers/status/servers/server/index.js, src/reducers/status/servers/server/test.js, src/reducers/status/servers/test.js, src/reducers/status/test.js, src/store/enhancer/index.js, src/store/enhancer/jobs-middleware/index.js, src/store/enhancer/location-middleware/index.js, src/store/enhancer/status-middleware/index.js, src/utils/global-message/index.js, src/utils/global-message/test.js
Added a background loop to check the status of the different servers the client depends on, and display the corresponding information in the UI.
=> Background loop

src/components/File/index.js, src/components/File/style.css, src/components/Matches/FileExporter/index.js, src/components/Matches/index.js, src/components/SearchResults/__snapshots__/test.js.snap, src/components/SearchResults/index.js, src/components/Table/Exporter/style.css, src/pages/Entry/index.js, src/pages/Protein/index.js, src/pages/Proteome/index.js, src/pages/Set/index.js, src/pages/Structure/index.js, src/pages/Taxonomy/index.js, src/subPages/SimilarProteins/index.js
Changing all the export buttons as requested in the UX story
=> Export table buttons

package.json, scripts/create-sitemap.js, src/actions/creators/index.js, src/actions/types/index.js, src/components/IPScan/Status/__snapshots__/test.js.snap, src/components/IPScan/Status/index.js, src/components/IPScan/Status/style.css, src/components/IPScan/Summary/index.js, src/components/IPScan/Summary/style.css, src/components/ProtVista/style.css, src/components/Protein/ProteinEntryHierarchy/index.js, src/components/Proteome/EntryHierarchy/index.js, src/components/Proteome/Focus/index.js, src/components/Set/Summary/index.js, src/components/SimpleCommonComponents/Loading/spinningCircle/index.js, src/components/SimpleCommonComponents/Loading/spinningCircle/style.css, src/components/Title/index.js, src/index.js, src/pages/Download/index.js, src/pages/Home/index.js, src/pages/Release_notes/index.js, src/pages/Sequence/index.js, src/schema_org/processors.js, src/snippets/template.py.tmpl, src/store/enhancer/jobs-middleware/index.js, src/subPages/Sequence/index.js
* Release notes have an array of notes that was rendering a 0 when empty. now fixed
* python3 template script now includes a variable to attempt a failed query up to 3 times
* Solving #221 and #226 
* adding a `create-sitemap` script
=> Minor changes in DEV

config.yml.example, package.json, src/components/EntryMenu/EntryMenuLink/index.js, src/components/Help/Documentation/__snapshots__/test.js.snap, src/config.js, src/higherOrder/loadData/defaults/index.js, src/menuConfig.js, src/subPages/Curation/index.js, src/subPages/index.js
Curation has to be added in `config.yml ` under entry subpages.
=> Curation tab added to Pfam entries

src/pages/error/NotFound/__snapshots__/test.js.snap, src/pages/error/NotFound/index.js, src/pages/error/NotFound/styles.css
=> Legacy endpoint

src/components/DownloadForm/Controls/index.js, src/components/File/index.js, src/components/IPScan/Search/index.js, src/pages/Settings/index.js, src/reducers/download/index.js, src/store/enhancer/jobs-middleware/index.js, src/utils/browser-notifications/index.js
Both the sequence search and download support browser notifications and there is an option to enable them in the settings page.
I have removed the click event for download as it caused page refresh and the redux state for download is lost. If there is any way to retain it, please direct me. I will add it.
=> Browser notifications

src/components/SimpleCommonComponents/FullScreenButton/index.js, src/components/Structure/Viewer/index.js, src/components/Structure/Viewer/style.css
Re-factory of the fullscreen logic in the structure page after finding bug reported in #282
=> fixing bug with fullscreen in structure page

src/components/Genome3D/index.js, src/components/ProtVista/index.js, src/components/Related/DomainEntriesOnStructure/index.js
It includes very minor improvements in the structures part of the story - https://www.ebi.ac.uk/panda/jira/secure/RapidBoard.jspa?rapidView=48&projectKey=IBU&view=planning&selectedIssue=IBU-8663&epics=visible&issueLimit=100&selectedEpic=IBU-8930.
Apart from that, the labels are truncated to show just the name (In this case the source). G3D: and the type are removed
=> Genome3d improvements

src/components/IPScan/Summary/index.js, src/components/Protein/Sequence/IPScanButton/index.js, src/components/Protein/Sequence/__snapshots__/test.js.snap, src/components/Protein/Sequence/index.js, src/components/Protein/Summary/__snapshots__/test.js.snap, src/components/Protein/Summary/index.js, src/components/SimpleCommonComponents/DropDownButton/index.js, src/components/SimpleCommonComponents/DropDownButton/style.css, src/components/Table/Exporter/index.js
* It includes the show/disable button changes for the export button in InterProScan result page. For locally stored results, if they are deleted in our server (past 7 days), only JSON can be downloaded and other options are greyed out.
* Search with InterProScan option is added to protein page
=> Ipscan minor changes

src/components/IPScan/Summary/index.js, src/components/SearchByText/TextSearchBox.js, src/components/home/SearchHistory/index.js, src/components/home/SearchHistory/styles.css, src/pages/Home/index.js, src/storage/searchStorage.js
When the user types and the search is triggered, thats when the search term is stored in local. So the same DEBOUNCE RATE is used. 
My question is when the user makes a selection from the search results, it has to be stored too right? Like they type a keyword, and goes for a particular entry, that entry would be his recent search isn't it?
=> Search terms stored in local storage and displayed in home page

.flowconfig, package.json, src/components/IPScan/DownloadTable/__snapshots__/test.js.snap, src/components/IPScan/DownloadTable/index.js, src/components/Table/views/Tree/index.js, src/pages/Download/index.js
Fixes https://www.ebi.ac.uk/interpro/entry/panther/PTHR46931/taxonomy/uniprot/#tree and links on Download page
=> Hotfix entry treeview

src/components/ContentFromRST/index.js, src/components/Download/Actions/index.js, src/components/Entry/EntryListFilters/EntryTypeFilter.js, src/components/Protein/ProteinListFilters/CurationFilter.js, src/components/Protein/ProteinListFilters/MatchPresenceFilter.js, src/components/ToggleSwitch/style.css, src/pages/Download/index.js, src/pages/Entry/index.js, src/pages/Protein/index.js, src/pages/Release_notes/index.js, src/subPages/SimilarProteins/index.js, src/subPages/SimilarProteins/style.css, src/subPages/index.js
A few fixes/improvements for minor issues, including #318, #320, #323, and #329.
=> Misc fixes

src/components/ProtVista/Popup/Entry/index.js, src/components/ProtVista/Popup/Residue/index.js, src/components/ProtVista/Popup/index.js, src/components/ProtVista/index.js, src/components/ProtVista/style.css, src/components/Related/DomainsOnProtein/index.js, src/utils/entry-color/index.js
The residues are moved to a separate section in the protein viewer. PIRSR residues are shown just like the rest.
=> Residue track

src/components/Structure/Viewer/index.js
This should create a short label in the viewer when hovering over a protein residue. It works but appears to gradually degrade performance. I'm not sure whether this is due to the way I'm handling the events or if it's specific to me laptop (which is rather old and struggles running VScode and devtools)
=> new hover listener

src/components/EntryMenu/EntryMenuLink/AlphaFoldMenuLink.js, src/components/ProtVista/Options/index.js, src/components/ProtVista/index.js, src/components/ProtVista/style.css, src/components/Related/DomainsOnProtein/index.js, src/components/Set/Summary/index.js, src/components/Settings/Advanced/index.js, src/components/generic/Link/utils/generate-classname/index.js, src/pages/Settings/index.js, src/pages/Settings/styles.css, src/reducers/settings/category/index.js, src/store/enhancer/location-middleware/index.js
It adds the option `Short Name` to the labels in the feature viewer.
The options are now kept in the redux state instead of the component state, to make this option permanent and be reflected in future uses of the feature viewer.
The option can now also be change in the settings page.
Bonus commit: 💅 Styling the settings page
*note*: I'll open a different PR to deal with the short names in the clan viewer
=> Short name in feature viewer

package-lock.json, src/components/SearchResults/ExactMatch/Gene/index.js, src/components/SearchResults/ExactMatch/index.js, src/components/SearchResults/__snapshots__/test.js.snap, src/components/SearchResults/style.css, src/components/SearchResults/test.js
Added support to the search functionality. If the user starts a search using a gene name proteins from the key organisms will be retrieved as suggestions of an exact gene match.
It also reenables the search by entry_name.
Add some tests for `<ExactMatch />`
=> exact search by gene

src/pages/Home/index.js, src/pages/Home/style.css
Update the message on the home page
=> Pfam blog post

src/components/Set/Summary/index.js, src/main.js, src/utils/processDescription/getURLbyAccession/index.js, src/utils/processDescription/handlers/index.js
Resolves #399 
Updates the description object with the source database of the clan so the URL is `/set/<database>/<accession>/` instead of `/set/all/<accession>`.
=> Fix clan search

src/components/AlphaFold/ProteinTable/index.js, src/subPages/AlphaFoldModelSubPage/index.js
This PR fixes a bug introduced by #412, where an issue is raised in the AlphaFold sub-page for non-InterPro entries.
=> Alphafold all entries

src/components/Entry/DomainArchitectures/__snapshots__/test.js.snap, src/components/Entry/DomainArchitectures/index.js, src/components/Entry/DomainArchitectures/style.css, src/components/Matches/index.js, src/components/ProtVista/style.css, src/components/Title/index.js, src/components/Title/style.css, src/higherOrder/loadData/defaults/index.js
3 minor fixes:
* IDA results -width scalable to the longest protein in the page
* Short name in the list of entries of a clan
* Adding fragment tag to proteins
=> Feedback pfam

src/components/AlphaFold/Model/index.js, src/components/AlphaFold/Model/style.css, src/components/ContentFromRST/index.js, src/components/File/style.css, src/components/Menu/DynamicMenu/__snapshots__/test.js.snap, src/components/Structure/ViewerAndEntries/button-bar.css, src/components/Structure/ViewerAndEntries/index.js, src/components/Title/index.js, src/menuConfig.js, src/pages/About/index.js, src/pages/Entry/index.js, src/pages/Help/index.js
A few minor changes to be deployed:
- Including License page in About
- Including protein families game in Help
- Fixing the title of the proteins to include their name
- same style buttons for structure/alphafold viewers
=> minor fixes

src/components/IPScan/Summary/serializers.js
The InterProScan results include a protein viewer, this one however was displaying some categories in a different way than the viewer in the protein pages.
Some of the inconsistencies were:
* The category called Predictions should be Other features
* Funfam where displayed as Unintegrated features
* PIRSR residues were displayed as features.
* Residues were displayed together with their associated entries. However, in the protein viewers, those are displayed in a separate category.
=> organizing the tracks in the ipscan results

src/components/GoTerms/__snapshots__/test.js.snap, src/components/GoTerms/index.tsx, src/components/GoTerms/test.js, src/components/IPScan/Summary/index.js, src/components/TimeAgo/__snapshots__/test.js.snap
This PR shows reported PANTHER GO terms in the InterProScan results (below InterPro GO terms). 
We can test with this JSON output: [test_all_appl.fasta.json.zip](https://github.com/ProteinsWebTeam/interpro7-client/files/11750660/test_all_appl.fasta.json.zip)
=> InterProScan - PANTHER2GO

src/components/Matches/EntriesOnProtein/index.tsx, src/components/Related/RelatedAdvanced/index.tsx, src/subPages/SimilarProteins/index.js
Fixes #514 and #515. 
You do not need to have a local API up and running, you can use `https://wwwdev.ebi.ac.uk/interpro/api/` or `https://www.ebi.ac.uk/interpro/api/`.
=> Post release fixes

src/components/Entry/Summary/SidePanel/index.tsx, src/components/SimpleCommonComponents/Tooltip/index.tsx, src/components/SimpleCommonComponents/Tooltip/style.css
When submitting an annotation from a Pfam entry page, the email is sent to the Pfam helpdesk instead of the InterPro helpdesk.
Local copy on the `dev` branch, or `http://wp-np3-af.ebi.ac.uk/interpro/api/`.
=> Pfam helpdesk

src/components/Description/DescriptionLLM/__snapshots__/test.js.snap, src/components/Description/DescriptionLLM/index.tsx
Reduces the footprint of the LLM warning message
=> Downsizing the LLM warning

src/components/Table/Footer/index.js
adding pivot pages if there are too many pages in numeric pagination
=> improving numeric pagination

scripts/README.md, scripts/browse-with-puppetteer.js
Fixed #602.
Please check that no error occurs on a local instance of this repo (`dev` branch).
=> Post-release fix

config.yml.example, src/components/home/EBISurvey/index.tsx, src/pages/Home/index.js
Adding the banner details as a Callout on the Home page.
**NOTE:** Only to be merged the 20th May
=> EBI survey banner in home page

src/components/Table/FullyLoadedTable/index.tsx, src/subPages/Interactions/index.tsx
This PR adds links to IntAct and EuropePMC for the IntAct entries listed in the _interactions_ subpage of InterPro entries.
=> Additional links in interactions page

.husky/pre-commit, src/components/Entry/Card/index.tsx, src/components/Entry/Card/styles.css, src/components/SimpleCommonComponents/Card/CounterIcon/styles.css, src/components/SimpleCommonComponents/Card/styles.css, src/higherOrder/loadData/defaults/index.js, src/higherOrder/loadData/defaults/test.js
Removed the description and its related logic (as discussed with @gustavo-salazar). 
The result comes dows to this:
The fix for the husky pre-commit file is to prevent running into the `command not found` error for lint-staged (@gustavo-salazar suggests that it might happen if `./node_modules/.bin/ ` is not added to PATH).
=> Removed description from EntryCard and changed husky configuration

src/components/DownloadForm/index.tsx, src/components/Matches/index.tsx, src/components/home/BySpecies/__snapshots__/test.js.snap, src/components/home/BySpecies/index.js, src/pages/Home/index.js, src/staticData/home.js
This PR addresses the minor changes requested in:
- [IBU-11440](https://www.ebi.ac.uk/panda/jira/browse/IBU-11440)
- [IBU-11441](https://www.ebi.ac.uk/panda/jira/browse/IBU-11441)
- [IBU-11446](https://www.ebi.ac.uk/panda/jira/browse/IBU-11446)
=> ScriptGen in subpages + Search propagated to ScriptGen + Homepage browsing by tab changes

src/components/ProteinViewer/TracksInCategory/index.tsx
=> Remove listener logic causing some tooltips to not be displayed

src/components/IPScan/Summary/serializers.ts, src/types/external-payloads.d.ts
=> Fix IPScan representative data

src/subPages/Feedback/index.tsx
Instead of showing a toast at the bottom right corner, display a Callout above the form to let the user know that the feedback has been sent successfully.
=> Fix feedback notification

src/components/Help/Publication/index.tsx, src/pages/Home/index.js
This PR addresses [IBU-12083](https://embl.atlassian.net/browse/IBU-12083)
=> Pfam citation on home page

src/components/Set/Summary/index.tsx
=> Hide literature section if there are not lit. references
